/**
 * The webview's scripts, relative to media/, in load order.
 *
 * The helpers are self-contained and load as separate classic scripts. The
 * editor itself is one bundle built from media/editor/*.js by
 * build/bundle-webview.js (`npm run compile`): those files share a global
 * scope and rely on hoisting across all of them, which only holds within a
 * single script.
 */
export const WEBVIEW_HELPER_SCRIPTS: readonly string[] = [
    'polygon-clipping.umd.min.js',
    'samPromptHelpers.js',
    'mergeShapesHelpers.js',
    'shapeHelpers.js',
    'notifyBusHelpers.js',
    'notifyBus.js',
    'tipsData.js',
    'tooltipHelpers.js',
    'tooltip.js',
    'popoverDismiss.js',
    'advancedSearchHelpers.js',
    'labelSelectionHelpers.js',
    'keybindings.js',
    'i18n.js',
];

/** Generated by build/bundle-webview.js; keep the name in sync with it. */
export const EDITOR_BUNDLE = 'editor.bundle.js';

export const WEBVIEW_SCRIPTS: readonly string[] = [...WEBVIEW_HELPER_SCRIPTS, EDITOR_BUNDLE];
